# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Athink_
subtitle: 自由源于努力
description: 博客||分享生活点滴·分享技术成长
keywords: 技术,博客,Athink,自由,新浪博客,专栏,网易博客,blog,百度
author: Athink_
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.onfree.cn
root: /
permalink: posts/:abbrlink.html
permalink_defaults: 
pretty_urls:
  #trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  #trailing_html: false # Set to false to remove trailing '.html' from permalinks

abbrlink:
 alg: crc32 #算法： crc16(default) and crc32
 rep: hex   #进制： dec(default) and hex: dec #输出进制：十进制和十六进制，默认为10进制。丨dec为十进制，hex为十六进制  

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
 - README.md
 #- 'mylove/**'
 

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 9
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 9
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
#theme: next
theme: hexo-theme-matery-master

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    - git@e.coding.net:athink8/athink8.git,master
    - https://github.com/athink8/athink8.github.io.git,master
  branch: master
  #github: https://github.com/athink8/athink8.github.io.git,master
  #coding: git@e.coding.net:athink8/athink8.git,master
  
#代码高亮
highlight:
  enable: false
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
  custom_css:
  
#搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 100
  
#中文链接转拼音
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

#添加emoji表情支持
githubEmojis:
  enable: false
  className: github-emoji
  inject: true
  styles:
   customEmojis
  
#懒加载
# 当 src=url 这样写法时懒加载失效
lazyload:
 enable: true 
 onlypost: false
 loadingImg:  # eg ./images/loading.gif

#hexo-admin  密码 bcrypt 加密
admin:
 username: athink
 password_hash: $2a$10$k5EJHzUWt7dLofOKQd/gFeaXq3SVsxs1QUQTQGogH/mszMm8pcETu 
 secret: hello athink
 #deployCommand: './admin_script/hexo-generate.sh'
 expire: 60*1
 
 #链跳转插件
 hexo_external_link:
  enable: true
  enable_base64_encode: true
  url_param_name: '' #u
  html_file_name: 'go.html'
  target_blank: true
  link_rel: 'external nofollow noopener noreferrer'
  domain: blog.onfree.cn' # 如果开启了防盗链
  safety_chain: true
  
#自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#主动推送  
baidu_url_submit:
  count: 5 ## 提交最新的五个链接
  host: https://blog.onfree.cn ## 百度站长平台中注册的域名
  token: s4uxGbZAao0v0aln ## 准入秘钥
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里